<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','history');
$coreDefs['dashlets'][0]['filter']['module'] = array('WPM_Waste_Profile_Module');
$coreDefs['tabs'][0]['link'] = 'wpm_waste_profile_module_activities_1_meetings';
$coreDefs['tabs'][1]['link'] = 'wpm_waste_profile_module_activities_1_emails';
$coreDefs['tabs'][2]['link'] = 'wpm_waste_profile_module_activities_1_calls';
$coreDefs['custom_toolbar']['buttons'][0]['buttons'][0]['params']['link'] = 'wpm_waste_profile_module_activities_1_emails';
$viewdefs['WPM_Waste_Profile_Module']['base']['view']['history'] = $coreDefs;
