<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','attachments');
$coreDefs['dashlets'][0]['filter']['module'] = array('WPM_Waste_Profile_Module');
$coreDefs['dashlets'][0]['config']['link'] = 'wpm_waste_profile_module_activities_1_notes';
$coreDefs['dashlets'][0]['preview']['link'] = 'wpm_waste_profile_module_activities_1_notes';
$viewdefs['WPM_Waste_Profile_Module']['base']['view']['attachments'] = $coreDefs;
