<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','attachments');
$coreDefs['dashlets'][0]['filter']['module'] = array('HT_Manifest');
$coreDefs['dashlets'][0]['config']['link'] = 'ht_manifest_activities_1_notes';
$coreDefs['dashlets'][0]['preview']['link'] = 'ht_manifest_activities_1_notes';
$viewdefs['HT_Manifest']['base']['view']['attachments'] = $coreDefs;
