<?php

$dictionary['RevenueLineItem']['fields']['related_rli_total_c'] = array(
    'duplicate_merge_dom_value' => 0,
    'labelValue' => 'Related RLI Total',
    'calculated' => '1',
    'formula' => 'rollupSum($revenuelineitems_revenuelineitems_1,"total_amount")',
    'enforced' => '1',
    'dependency' => '',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'related_rli_total_c',
    'vname' => 'LBL_RELATED_RLI_TOTAL',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'false',
    'duplicate_merge' => 'disabled',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'len' => 18,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
//    'id' => 'RevenueLineItemsrelated_rli_total_c',
    'custom_module' => 'RevenueLineItems',
);
