<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['waste_constituents'] = array(
    'table' => 'waste_constituents',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array(
        'min' =>
        array(
            'required' => false,
            'name' => 'min',
            'vname' => 'LBL_MIN',
            'type' => 'decimal',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'default' => '',
            'calculated' => false,
            'enable_range_search' => false,
            'precision' => 2,
            'len' => '26,2',
        ),
        'max' =>
        array(
            'required' => false,
            'name' => 'max',
            'vname' => 'LBL_MAX',
            'type' => 'decimal',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'default' => '',
            'calculated' => false,
            'enable_range_search' => false,
            'precision' => 2,
            'len' => '26,2',
        ),
        'uom' =>
        array(
            'required' => false,
            'name' => 'uom',
            'vname' => 'LBL_UOM',
            'type' => 'enum',
            'massupdate' => true,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'default' => '',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'uom_list',
            'dependency' => false,
        ),
        'epa_waste_code' =>
        array(
            'required' => false,
            'name' => 'epa_waste_code',
            'vname' => 'LBL_EPA_WASTE_CODE',
            'type' => 'enum',
            'massupdate' => true,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'default' => '',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'WP_EPA_CODES',
            'dependency' => false,
        ),
        'rcra' =>
        array(
            'required' => false,
            'name' => 'rcra',
            'vname' => 'LBL_RCRA',
            'type' => 'varchar',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'full_text_search' =>
            array(
                'enabled' => '0',
                'boost' => '1',
                'searchable' => false,
            ),
            'calculated' => 'true',
            'formula' => '$epa_waste_code',
            'enforced' => true,
            'len' => '255',
            'size' => '20',
        ),
        'type' =>
        array(
            'required' => false,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'full_text_search' =>
            array(
                'enabled' => '0',
                'boost' => '1',
                'searchable' => false,
            ),
            'len' => '255',
            'options' => 'waste_constituents_type_list',
            'size' => '20',
        ),
        'other' =>
        array(
            'required' => false,
            'name' => 'other',
            'vname' => 'LBL_CONSTITUENT_OTHER_NAME',
            'type' => 'varchar',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'full_text_search' =>
            array(
                'enabled' => '0',
                'boost' => '1',
                'searchable' => false,
            ),
            'len' => '255',
            'size' => '20',
        ),
        'regulated_metals' =>
        array(
            'required' => false,
            'name' => 'regulated_metals',
            'vname' => 'LBL_REGULATED_METALS',
            'type' => 'varchar',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'full_text_search' =>
            array(
                'enabled' => '0',
                'boost' => '1',
                'searchable' => false,
            ),
            'calculated' => 'true',
            'formula' => 'getDropdownValue("WP_EPA_CODES",$epa_waste_code)',
            'enforced' => true,
            'len' => '255',
            'size' => '20',
        ),
        'regulatory_level' =>
        array(
            'required' => false,
            'name' => 'regulatory_level',
            'vname' => 'LBL_REGULATORY_LEVEL',
            'type' => 'decimal',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'default' => '',
            'calculated' => false,
            'enable_range_search' => false,
            'precision' => 2,
            'len' => '26,2',
        ),
        'tclp' =>
        array(
            'required' => false,
            'name' => 'tclp',
            'vname' => 'LBL_TCLP',
            'type' => 'decimal',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'default' => '',
            'calculated' => false,
            'enable_range_search' => false,
            'precision' => 2,
            'len' => '26,2',
        ),
        'not_applicable' =>
        array(
            'required' => false,
            'name' => 'not_applicable',
            'vname' => 'LBL_NOT_APPLICABLE',
            'type' => 'bool',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'pii' => false,
            'default' => false,
            'calculated' => false,
            'size' => '20',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if (!class_exists('VardefManager')) {
    
}
VardefManager::createVardef('waste_constituents', 'waste_constituents', array('basic', 'team_security', 'assignable', 'taggable'));
