<?php

$dictionary['mv_Attachments']['fields']['image'] = array(
    'dependency' => 'contains($file_mime_type,"image")',
    'required' => false,
    'name' => 'image',
    'vname' => 'LBL_IMAGE',
    'type' => 'image',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 255,
    'size' => '20',
    'studio' => 'visible',
    'dbType' => 'varchar',
    'width' => '425',
    'readonly' => true,
    'border' => '',
    'height' => '',
);
