<?php

//$dictionary["OutboundEmail"]["fields"]["user_signature_name"] = array(
//    'dependency' => '',
//    'required' => false,
//    'source' => 'non-db',
//    'name' => 'user_signature_name',
//    'vname' => 'LBL_PDF_TEMPLATE_TYPE',
//    'type' => 'relate',
//    'massupdate' => false,
//    'no_default' => false,
//    'comments' => '',
//    'help' => '',
//    'importable' => 'true',
//    'duplicate_merge' => 'enabled',
//    'duplicate_merge_dom_value' => 1,
//    'audited' => false,
//    'reportable' => true,
//    'unified_search' => false,
//    'merge_filter' => 'disabled',
//    'pii' => false,
//    'calculated' => false,
//    'len' => 255,
//    'size' => '20',
//    'id_name' => 'user_signature_id',
//    'table' => 'users_signatures',
//    'module' => 'UserSignatures',
//    'rname' => 'name',
//    'quicksearch' => 'enabled',
//    'studio' => 'visible',
//    'hideacl' => true,
//);
//
//$dictionary["OutboundEmail"]["fields"]["user_signature_id"] = array(
//    'required' => false,
//    'name' => 'user_signature_id',
//    'vname' => 'LBL_PDF_TEMPLATE_TYPE',
//    'type' => 'id',
//    'massupdate' => false,
//    'no_default' => false,
//    'comments' => '',
//    'help' => '',
//    'importable' => 'true',
//    'duplicate_merge' => 'enabled',
//    'duplicate_merge_dom_value' => 1,
//    'audited' => false,
//    'reportable' => false,
//    'unified_search' => false,
//    'merge_filter' => 'disabled',
//    'pii' => false,
//    'calculated' => false,
//    'len' => 36,
//    'size' => '20',
//    'hideacl' => true,
//    'table' => 'users_signatures',
//    'module' => 'UserSignatures',
//);
//
//$dictionary["OutboundEmail"]["fields"]["signature_id_varchar"] = array(
//    'name' => 'signature_id_varchar',
//    'vname' => 'LBL_SIGNATURE_ID_VARCHAR',
//    'type' => 'varchar',
//    'len' => 9,
//    'size' => '20',
//);