<?php

//$dictionary["PdfManager"]["fields"]["pdf_template_type"] = array(
//    'required' => false,
//    'name' => 'pdf_template_type',
//    'vname' => 'LBL_PDF_TEMPLATE_TYPE',
//    'type' => 'enum',
//    'massupdate' => false,
//    'len' => 100,
//    'size' => '20',
//    'options' => 'pdf_template_type_list',
//);

$dictionary["PdfManager"]["fields"]["pdf_template_type_name"] = array(
    'dependency' => '',
    'required' => false,
    'source' => 'non-db',
    'name' => 'pdf_template_type_name',
    'vname' => 'LBL_PDF_TEMPLATE_TYPE',
    'type' => 'relate',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 255,
    'size' => '20',
    'id_name' => 'pdf_template_type_id',
    'module' => 'pdf_template_types',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
);

$dictionary["PdfManager"]["fields"]["pdf_template_type_id"] = array(
    'required' => false,
    'name' => 'pdf_template_type_id',
    'vname' => 'LBL_PDF_TEMPLATE_TYPE',
    'type' => 'id',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 36,
    'size' => '20',
);
