<?php

$dictionary["PdfManager"]["fields"]["header_html"] = array(
    'required' => false,
    'name' => 'header_html',
    'vname' => 'LBL_HEADER_HTML',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'studio' => false,
    'rows' => '8',
    'cols' => '160',
    'dependency' => false,
);

$dictionary["PdfManager"]["fields"]["footer_html"] = array(
    'required' => false,
    'name' => 'footer_html',
    'vname' => 'LBL_FOOTER_HTML',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'studio' => false,
    'rows' => '8',
    'cols' => '160',
    'dependency' => false,
);
