<?php

$dictionary['PNL_Permits_Licenses']['fields']['license_preview_c'] = array(
    'labelValue' => 'License Preview',
    'dependency' => '',
    'dbType' => 'text',
    'len' => '',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'license_preview_c',
    'vname' => 'LBL_LICENSE_PREVIEW',
    'type' => 'iframe',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'size' => '20',
    'gen' => '1',
    'link_target' => '350',
    'height' => '350',
);
