<?php

$viewdefs['ProductTemplates'] = array(
    'base' =>
    array(
        'view' =>
        array(
            'list' =>
            array(
                'panels' =>
                array(
                    0 =>
                    array(
                        'name' => 'panel_header',
                        'fields' =>
                        array(
                            0 =>
                            array(
                                'name' => 'mft_part_num',
                                'label' => 'LBL_MFT_PART_NUM',
                                'enabled' => true,
                                'default' => true,
                                'width' => 'xsmall',
                            ),
                            1 =>
                            array(
                                'name' => 'name',
                                'link' => true,
                                'enabled' => true,
                                'default' => true,
                                'related_fields' =>
                                array_merge(array(
                                    'type_link',
                                    'mft_part_num',
                                    'vendor_part_num',
                                    'date_cost_price',
                                    'cost_price',
                                    'discount_price',
                                    'list_price',
                                    'cost_usdollar',
                                    'discount_usdollar',
                                    'list_usdollar',
                                    'tax_class',
                                    'date_available',
                                    'website',
                                    'weight',
                                    'qty_in_stock',
                                    'support_name',
                                    'support_description',
                                    'support_contact',
                                    'support_term',
                                    'pricing_factor',
                                    'following',
                                    'my_favorite',
                                    'tag',
                                    'locked_fields',
                                    'assigned_user_id',
                                    'assigned_user_name',
                                    'assigned_user_link',
                                    'currency_id',
                                    'base_rate',
                                    'currency_name',
                                    'currencies',
                                    'currency_symbol',
                                    'product_list_name_c',
                                    'product_uom_c',
                                    'product_vendor_c',
                                    'vendor_product_svc_descrp_c',
                                    'waste_profile_rqrd_c',
                                    'product_code_sku_c',
                                    'state_regulated_c',
                                    'shipping_ca_name_c',
                                    'shipping_hazardous_materia_c',
                                    'product_svc_description_c',
                                    'proper_shipping_name_c',
                                    'waste_state_codes_c',
                                    'product_templates_product_templates_1_name',
                                    'product_templates_product_templates_1_right',
                                    'product_templates_product_templates_1product_templates_ida',
                                    'is_bundle_product_c',
                                    'epa_code_1_c',
                                    'epa_code_2_c',
                                    'epa_code_3_c',
                                    'epa_code_4_c',
                                    'state_code_2_c',
                                    'state_code_3_c',
                                    'v_vendors_id_c',
                                    'position',
                                    'product_template_id',
                                    'product_template_name',
                                    'likely_case',
                                    'best_case',
                                    'worst_case',
                                    'line_number',
                                    'mft_part_num',
                                    'is_group_item_c',
                                    'name',
                                    'is_group_item_c',
                                    'type_name',
                                    'category_name',
                                    'mft_part_num',
                                    'product_code_sku_c',
                                    'product_list_name_c',
                                    'product_svc_description_c',
                                    'mandatory_print_text_c',
                                    'description',
                                    'additional_info_ack_c',
                                    'hide_price_from_paperwork_c',
                                    'fed_percentage',
                                    'discount_price',
                                    'product_uom_c',
                                    'pricing_formula',
                                    'weight',
                                    'bundle_total_c',
                                    'tax_class',
                                    'base_rate',
                                    'vendor_only_c',
                                    'standalone_item_c',
                                    'product_vendor_c',
                                    'vendor_part_num',
                                    'cost_price',
                                    'date_cost_price',
                                    'list_price',
                                    'vendor_product_svc_descrp_c',
                                    'customer_certificates',
                                    'transporter_certificates',
                                    'consignee_certificates',
                                    'shipping_hazardous_materia_c',
                                    'state_regulated_c',
                                    'manifest_required_c',
                                    'waste_profile_c',
                                    'waste_profile_relate_c',
                                    'proper_shipping_name_c',
                                    'waste_state_codes_c',
                                    'epa_waste_codes_c',
                                    'erg_no_c',
                                    'manifest_hazmat_handle_code_c',
                                    'manifest_container_type_c',
                                    'manifest_uom_c',
                                    'manifest_additional_info_c',
                                    'qty_in_stock',
                                    'website',
                                    'date_available',
                                    'manufacturer_name',
                                    'status',
                                    'support_name',
                                    'support_contact',
                                    'support_term',
                                    'support_description',
                                    'created_by_name',
                                    'modified_by_name',
                                    'date_entered',
                                    'date_modified',
                                    'commentlog',
                                    'audit',
                                    'line_number',
                                    'discount_usdollar',
                                    'currency_id',
                                    'v_vendors_id_c',
                                    'cost_usdollar',
                                    'list_usdollar',
                                        ), getViewFields('recordview', 'ProductTemplates')),
                                'width' => 'medium',
                            ),
                            2 =>
                            array(
                                'name' => 'type_name',
                                'enabled' => true,
                                'default' => true,
                            ),
                            3 =>
                            array(
                                'name' => 'category_name',
                                'enabled' => true,
                                'default' => true,
                            ),
                            4 =>
                            array(
                                'name' => 'discount_price',
                                'type' => 'currency',
                                'related_fields' =>
                                array(
                                    0 => 'discount_usdollar',
                                    1 => 'currency_id',
                                    2 => 'base_rate',
                                ),
                                'currency_field' => 'currency_id',
                                'base_rate_field' => 'base_rate',
                                'enabled' => true,
                                'default' => true,
                            ),
                            5 =>
                            array(
                                'name' => 'product_uom_c',
                                'label' => 'LBL_PRODUCT_UOM',
                                'enabled' => true,
                                'default' => true,
                                'width' => 'xsmall',
                            ),
                            6 =>
                            array(
                                'name' => 'list_price',
                                'type' => 'currency',
                                'related_fields' =>
                                array(
                                    0 => 'list_usdollar',
                                    1 => 'currency_id',
                                    2 => 'base_rate',
                                ),
                                'currency_field' => 'currency_id',
                                'base_rate_field' => 'base_rate',
                                'enabled' => true,
                                'default' => true,
                            ),
                            7 =>
                            array(
                                'name' => 'cost_price',
                                'type' => 'currency',
                                'related_fields' =>
                                array(
                                    0 => 'cost_usdollar',
                                    1 => 'currency_id',
                                    2 => 'base_rate',
                                ),
                                'currency_field' => 'currency_id',
                                'base_rate_field' => 'base_rate',
                                'enabled' => true,
                                'default' => true,
                            ),
                            8 =>
                            array(
                                'name' => 'product_list_name_c',
                                'label' => 'LBL_PRODUCT_LIST_NAME',
                                'enabled' => true,
                                'default' => true,
                            ),
                            9 =>
                            array(
                                'name' => 'product_vendor_c',
                                'label' => 'LBL_PRODUCT_VENDOR',
                                'enabled' => true,
                                'id' => 'V_VENDORS_ID_C',
                                'link' => true,
                                'sortable' => false,
                                'default' => true,
                                'type' => 'relate',
                            ),
                            10 =>
                            array(
                                'name' => 'date_entered',
                                'label' => 'LBL_DATE_ENTERED',
                                'enabled' => true,
                                'readonly' => true,
                                'default' => true,
                            ),
                            11 =>
                            array(
                                'name' => 'date_modified',
                                'label' => 'LBL_DATE_MODIFIED',
                                'enabled' => true,
                                'readonly' => true,
                                'default' => true,
                            ),
                            12 =>
                            array(
                                'name' => 'status',
                                'enabled' => true,
                                'default' => false,
                            ),
                            13 =>
                            array(
                                'name' => 'qty_in_stock',
                                'enabled' => true,
                                'default' => false,
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
);
