<?php

$dictionary['sales_and_services']['fields']['sales_and_service_total_c'] = array(
    'duplicate_merge_dom_value' => 0,
    'labelValue' => 'Sales Total',
    'calculated' => '1',
    'formula' => 'rollupSum($sales_and_services_revenuelineitems_1,"total_amount")',
    'enforced' => '1',
    'dependency' => '',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'sales_and_service_total_c',
    'vname' => 'LBL_SALES_AND_SERVICE_TOTAL',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'false',
    'duplicate_merge' => 'disabled',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'len' => 18,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
//    'id' => 'sales_and_servicessales_and_service_total_c',
    'custom_module' => 'sales_and_services',
);
