<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','active-tasks');
$coreDefs['dashlets'][0]['filter']['module'] = array('HT_Manifest');
$coreDefs['custom_toolbar']['buttons'][0]['buttons'][0]['params']['link'] = 'ht_manifest_activities_1_tasks';
$coreDefs['tabs'][0]['link'] = 'ht_manifest_activities_1_tasks';
$coreDefs['tabs'][1]['link'] = 'ht_manifest_activities_1_tasks';
$viewdefs['HT_Manifest']['base']['view']['active-tasks'] = $coreDefs;
