<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','inactive-tasks');
$coreDefs['dashlets'][0]['filter']['module'] = array('WPM_Waste_Profile_Module');
$coreDefs['custom_toolbar']['buttons'][0]['buttons'][0]['params']['link'] = 'wpm_waste_profile_module_activities_1_tasks';
$coreDefs['tabs'][0]['link'] = 'wpm_waste_profile_module_activities_1_tasks';
$coreDefs['tabs'][1]['link'] = 'wpm_waste_profile_module_activities_1_tasks';
$viewdefs['WPM_Waste_Profile_Module']['base']['view']['inactive-tasks'] = $coreDefs;
