<?php

$dictionary['ProductTemplate']['fields']['fed_percentage'] = array(
    'labelValue' => 'FED %',
    'enforced' => '',
    'dependency' => 'not(equal($is_bundle_product_c,"parent"))',
    'default' => '',
    'required' => false,
    'name' => 'fed_percentage',
    'vname' => 'LBL_FED_PERCENTAGE',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 12,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
);
