<?php

// created: 2019-06-17 16:45:12
$dictionary['Account']['fields']['physical_address_account_id']['name'] = 'physical_address_account_id';
$dictionary['Account']['fields']['physical_address_account_id']['type'] = 'id';
$dictionary['Account']['fields']['physical_address_account_id']['vname'] = 'LBL_PHYSICAL_ADDRESS_ACCOUNT_ID';
$dictionary['Account']['fields']['physical_address_account_id']['studio'] = false;
$dictionary['Account']['fields']['physical_address_account_name']['name'] = 'physical_address_account_name';
$dictionary['Account']['fields']['physical_address_account_name']['rname'] = 'name';
$dictionary['Account']['fields']['physical_address_account_name']['id_name'] = 'physical_address_account_id';
$dictionary['Account']['fields']['physical_address_account_name']['vname'] = 'LBL_PHYSICAL_ADDRESS_ACCOUNT_NAME';
$dictionary['Account']['fields']['physical_address_account_name']['type'] = 'relate';
$dictionary['Account']['fields']['physical_address_account_name']['isnull'] = 'true';
$dictionary['Account']['fields']['physical_address_account_name']['module'] = 'Accounts';
$dictionary['Account']['fields']['physical_address_account_name']['source'] = 'non-db';
$dictionary['Account']['fields']['physical_address_account_name']['studio'] = true;
//$dictionary['Account']['fields']['physical_address_account_name']['populate_list']['billing_address_street'] = 'physical_address_street';
//$dictionary['Account']['fields']['physical_address_account_name']['populate_list']['billing_address_city'] = 'physical_address_city';
//$dictionary['Account']['fields']['physical_address_account_name']['populate_list']['billing_address_state'] = 'physical_address_state';
//$dictionary['Account']['fields']['physical_address_account_name']['populate_list']['billing_address_postalcode'] = 'physical_address_postalcode';
//$dictionary['Account']['fields']['physical_address_account_name']['populate_list']['billing_address_country'] = 'physical_address_country';
// Below field(s) are added to get the Third Party billing address for PDF Templates.
$dictionary["Account"]["fields"]["third_party_billing_address_third_party_name"] = array(
    'labelValue' => 'Third Party Shipping Name',
    'source' => 'non-db',
    'name' => 'third_party_billing_address_third_party_name',
    'vname' => 'LBL_THIRD_PARTY_BILLING_ADDRESS_THIRD_PARTY_NAME',
    'type' => 'relate',
    'required' => false,
    'massupdate' => false,
    'no_default' => false,
    'importable' => false,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'studio' => false,
    'pii' => false,
    'calculated' => false,
    'len' => 255,
    'size' => '20',
    'id_name' => 'physical_address_account_id',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'billing_address_third_party_name',
);

$dictionary["Account"]["fields"]["third_party_billing_address_street"] = array(
    'labelValue' => 'Third Party Shipping Street',
    'source' => 'non-db',
    'name' => 'third_party_billing_address_street',
    'vname' => 'LBL_THIRD_PARTY_BILLING_ADDRESS_STREET',
    'type' => 'relate',
    'required' => false,
    'massupdate' => false,
    'no_default' => false,
    'importable' => false,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'studio' => false,
    'pii' => false,
    'calculated' => false,
    'len' => 255,
    'size' => '20',
    'id_name' => 'physical_address_account_id',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'billing_address_street',
);

$dictionary["Account"]["fields"]["third_party_billing_address_city"] = array(
    'labelValue' => 'Third Party Shipping City',
    'source' => 'non-db',
    'name' => 'third_party_billing_address_city',
    'vname' => 'LBL_THIRD_PARTY_BILLING_ADDRESS_CITY',
    'type' => 'relate',
    'required' => false,
    'massupdate' => false,
    'no_default' => false,
    'importable' => false,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'studio' => false,
    'pii' => false,
    'calculated' => false,
    'len' => 255,
    'size' => '20',
    'id_name' => 'physical_address_account_id',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'billing_address_city',
);

$dictionary["Account"]["fields"]["third_party_billing_address_state"] = array(
    'labelValue' => 'Third Party Shipping State',
    'source' => 'non-db',
    'name' => 'third_party_billing_address_state',
    'vname' => 'LBL_THIRD_PARTY_BILLING_ADDRESS_STATE',
    'type' => 'relate',
    'required' => false,
    'massupdate' => false,
    'no_default' => false,
    'importable' => false,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'studio' => false,
    'pii' => false,
    'calculated' => false,
    'len' => 255,
    'size' => '20',
    'id_name' => 'physical_address_account_id',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'billing_address_state',
);

$dictionary["Account"]["fields"]["third_party_billing_address_postalcode"] = array(
    'labelValue' => 'Third Party Shipping Postalcode',
    'source' => 'non-db',
    'name' => 'third_party_billing_address_postalcode',
    'vname' => 'LBL_THIRD_PARTY_BILLING_ADDRESS_POSTALCODE',
    'type' => 'relate',
    'required' => false,
    'massupdate' => false,
    'no_default' => false,
    'importable' => false,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'studio' => false,
    'pii' => false,
    'calculated' => false,
    'len' => 255,
    'size' => '20',
    'id_name' => 'physical_address_account_id',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'billing_address_postalcode',
);
